[package]
name = "common"
version = "0.2.0"
edition = "2024"

[dependencies]
uniffi = "0.28.3"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libaes = "0.7"

[lib]
crate-type = ["cdylib"]
# Put this only if you moved lib.rs.
path = "src/main/rust/lib.rs"