[package]
name = "common"
version = "0.5.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]
# Put this only if you moved lib.rs.
path = "src/main/rust/lib.rs"

[dependencies]
uniffi = "=0.29.3"